- R/DiagrammeR.R
As I was doing examples, I thought it might be a helpful feature for a diagram spec to be something like this.
```
DiagrammeR(
c("graph LR","A-->B;","C\n")
)
```
If we have `length > 1`, we could paste these together on the `R` side, so it will work correctly.
> add ability for a diagram to be a vector of character with length > 1

- inst/htmlwidgets/DiagrammeR.js
Likely an edge  case but currently `DiagrammeR` supports `tags$div(...,class="mermaid")` from `htmltools`  as another way to specify a diagram.  In this case `DiagrammeR()` simply injects dependencies, so the `htmlwidget` container will not have a `SVG`.  Check for this in `makeResponsive()`.
> fix makeResponsive

- inst/htmlwidgets/DiagrammeR.js
This is an attempt to use `try ... catch` with `mermaid.init()` to incorporate @jjallaire very good suggestion in #26 to send any `mermaid.js` errors (likely parse errors) to the `DiagrammeR` `htmlwidget`.  Since `mermaid.js` parses and renders in bulk, find the last processed `DiagrammeR` `div` since it should be the culprit.  As a couple of examples:
```
library(DiagrammeR)
dErr = DiagrammeR("graph LR; --;")
dErr
library(htmltools)
dGood = DiagrammeR("graph LR; A;")
html_print(tagList(dGood,dErr))
html_print(tagList(dErr,dGood))
html_print(tagList(dGood,dGood,dErr))
```
Could recurse until all done or found erroneous, but I think for now this solution will suffice.
> add try ... catch in Javascript to show error in the htmlwidget

- inst/htmlwidgets/DiagrammeR.yaml
- inst/htmlwidgets/lib/styles/styles.css
This ensures that error messages which are wider than the width of the htmlwidget div are still legible without scrolling.
> wrap error messages

- R/grViz.R
warn that `grViz` might not work on non-Windows RStudio viewer and almost definitely will not work on Windows RStudio viewer
> add warning for grVix in RStudio viewer since get strange error

- R/grViz.R
- inst/examples/graphviz_examples.R
@rich-iannone could you test on your machine?  I added one example in examples.R with `'` if that helps
> turn off call and fix "viewer" for warning; also sweep spec and replace ' with \]"

- R/grViz.R
Since `grViz` is very unreliable in RStudio Viewer, use `sizingPolicy` (thanks @jjallaire ) to suppress RStudio Viewer.
> suppress RStudio Viewer with `grViz`

- inst/htmlwidgets/DiagrammeR.js
This pull should allow `DiagrammeR` to work much better with Shiny #51.  I'll try to quickly explain what I changed.  `mermaid.init()` attempts to change all class `.mermaid` within a page and assigns an id with a simple counter to the SVG.  If we add or change a `mermaid` widget, and then rerun `mermaid.init()` the counter results in duplicated ids which is not allowable by CSS.  My original fix tried to wait until the final `mermaid` instance to run `mermaid.init()`.  However, asynchrony makes it difficult/impossible to know when we are ready to run.
The new solution changes the id assigned by `mermaid` to `mermaidChart-` + the id assigned to the `htmlwidget`.  Then, the problem becomes the CSS points to the old id, so we need to change this also.  Cross-browser differences cause this …
> fix mermaid shiny

- R/spectools.R
Add Razor-like syntax from @rich-iannone #37.  Only change made was to allow `*` whitespace between `\n` and `[0-9]`.  If accepted please re-roxygenize to document this new function and add to `NAMESPACE`.
> add Razor-like syntax

- inst/htmlwidgets/DiagrammeR.yaml
- inst/htmlwidgets/grViz.yaml
- inst/htmlwidgets/lib/styles/styles.css
This namespaces the styles dependency to DiagrammeR and also takes care of an issue in Bootstrap pages where labels used a white color in Bootstrap pages.
> provide distinct name for styles; ensure labels are black in bootstrap pages

- .Rbuildignore
- R/DiagrammeR.R
- R/mermaid.R
addressing warnings from CRAN submission:
1.  documented `...` for `mermaid` and `DiagrammeR`
2.  removed `type` from `mermaid` docs since not used
3.  added NEWS.md to .Rbuildignore
When `devtools::check()` no more warnings except those related to PDF vignette which are not applicable.
Please re-roxygenize.
> document ... in DiagrammeR and mermaid and add NEWS.md to .Rbuildignore for CRAN

- inst/htmlwidgets/DiagrammeR.js
When we made the changes to `mermaid` to work better in Shiny in https://github.com/rich-iannone/DiagrammeR/commit/8f078cad8e89d6271e5aeb5891277efb76d58814, I did not realize that sequence diagrams do not get an embedded stylesheet, so sequence diagrams stopped working.  This pull fixes that by looking for a stylesheet before changing.
> add check to style change in mermaid to fix bug with sequence

- DESCRIPTION
- R/graphviz_export.R
using the [gist](https://gist.github.com/jeroenooms/d0d03c7e58443f5a4438) from @jeroenooms as an example, add an `exportSVG` function to get the `SVG` for the rendered `grViz` diagram without the browser.  Since `viz.js` is such a large dependency, this can save significantly on the size of the HTML especially when converted by Pandoc into a single document.
Please re-roxygenize.  Feel free to change the name of the function if you don't like it.
Addresses #66 .
> add exportSVG to get SVG using V8 from @jeroenooms

- R/graphviz_single_df.R
Not sure if I just caught your `master` in a state of flux, but I discovered this missing `}`.
> missing closing bracket in graphviz_single_df

- README.md
The nycflights13 will fail at `%>>%` without a call to library(pipeR). See [SO post](http://stackoverflow.com/questions/30033856/diagrammer-example-leads-to-could-not-find-function-error).
> Add library(pipeR) to README.md

- R/delete_edge.R
- R/delete_node.R
When using either the `delete_edge` or `delete_node` functions, the updated graph object does not retain any of the graph attributes that may have been set when the original graph was created, such as `"layout = neato"`. I simply added the `graph_attrs` parameter to the `create_graph` calls within these functions to keep the original graph attributes.
> Preserve existing graph attributes when deleting nodes or edges

- R/delete_node.R
Before, it produced an empty nodes_df which made the create_graph
function to crash when trying to delete a node without edges.
> Fix delete_node for nodes without any edges

- R/create_graph.R
With this change if the pos column already exists it overwrites it. 
Previously it kept on adding columns named "pos".
This happened for example after using add_node.
> Change addition of the pos column to the nodes df

- R/create_graph.R
- R/get_edges.R
- R/get_nodes.R
- R/set_edge_attr.R
- R/set_node_attr.R
- tests/testthat/test-add_node_edge.R
- tests/testthat/test-add_node_edge_df.R
- tests/testthat/test-create_combine_edges.R
- tests/testthat/test-create_graph.R
- tests/testthat/test-datatablecompatability.R
- tests/testthat/test-import_graph.R
- tests/testthat/test-node_edge_info.R
Changed the `class(x)=="data.frame"` constructs to `inherit(x,"data.frame")` instead. There's still a few other `class(x)=="something"` else constructs in there though. May take a look and submit another PR if I get the time but I don't think they're as problematic.
> Converting code that produces warnings when using data.table or dplyr tables

- R/select_nodes_by_degree.R
Hi, 
reading the code to understand `select_nodes_by_degree`, I encounter a typo mistake in the if condition for logical expression.
To filter node ID values by degree type and degree values, condition `"^==.*"` was not present and `"^!=.*"` was here twice. So, I corrected in the if condition related to `"=="`.
> correction in if condition for logical expression

- inst/htmlwidgets/lib/mermaid/dist/mermaid.css
Fix for #149. I did not add the .mermaid class for .node. Getting that to work may require edits to the mermaid.js source code (see @timelyportfolio's comments in https://github.com/rich-iannone/DiagrammeR/pull/160)
Also added padding for .edgeLabels to avoid text being hidden in Firefox and Safari
> Add .mermaid class to CSS and padding to .edgeLabel in CSS for non-chrome browsers. 

- inst/htmlwidgets/lib/mermaid/dist/mermaid.css
The padding I added in the previous PR unfortunately also added spaces for mermaid graphs without labels. The issue I was seeing in Firefox and Safari was resolved by setting font-weight for labels explicitly.
> Use font-weight to address padding issues in Firefox and Safari

- R/grViz.R
This fixes #183. 
I tried in a terminal, a browser windows opens.
I tried in Rcloud, it works fine.
I tried in new RStudio, it works fine.
I didn't try in old RStudio, to be honest, but that should work, too.
Thanks!
> grViz: only exclude old RStudio viewer, allow others

- R/DiagrammeR.R
Allow height to adjust based on graph characteristics by setting `height = 'auto'`
> set height to auto in DiagrammeROuput

- R/print.R
Hi Richard Iannone,
Thanks for time you've spent making DiagrammeR. I've been using it for pipeline visualization in one of my packages. Anyway, I ran into a little issue with printing graphs. Here I've made two fixes to the print function.
1. Fixed a negative width case for whitespace on small consoles (first commit)
2. Fixed a little typo, where you probably meant to say 'edge' but wrote 'node'
This patch shouldn't change anything about how print works.
> Two minor fixes to the print function

- R/generate_dot.R
- tests/testthat/test-generate_dot.R
The `render_graph` throws an error, whenever 'cluster' is present as a node attribute. It is discussed in #257.
> Fix cluster rendering

- R/add_edge.R
- R/add_edges_from_table.R
- R/colorize_edge_attrs.R
- R/colorize_node_attrs.R
- R/delete_global_graph_attrs.R
- R/get_agg_degree_in.R
- R/get_agg_degree_out.R
- R/get_agg_degree_total.R
- R/get_edge_attrs.R
- R/get_edge_attrs_ws.R
- R/get_edge_ids.R
- R/get_edges.R
- R/get_node_attrs.R
- R/get_node_attrs_ws.R
- R/get_node_ids.R
- R/rescale_edge_attrs.R
- R/rescale_node_attrs.R
- R/select_edges.R
- R/select_nodes.R
- R/set_node_attrs_ws.R
- R/trav_both.R
- R/trav_both_edge.R
- R/trav_in.R
- R/trav_in_edge.R
- R/trav_in_node.R
- R/trav_in_until.R
- R/trav_out.R
- R/trav_out_edge.R
- R/trav_out_node.R
- R/trav_out_until.R
Hi Rich. Calling `UQ()` with the rlang namespace is deprecated as of rlang 0.3.0.
Could you please issue a quick patch release to CRAN? I'm planning to release 0.3.0 on Friday 19th and the warnings caused by diagrammeR trigger a check failure in processanimateR.
cc @fmannhardt
> Fix namespaced UQ()

- inst/htmlwidgets/grViz.js
The arguments being passed into vis.js are in the wrong format:
https://github.com/mdaines/viz.js/blob/v1.8.2/src/api.js#L2
vis.js expects a single options object containing all the desired settings.
Perhaps this was missed when upgrading vis.js versions?
This caused weird errors for me as I had extended the string prototype to contain a 'format' function
> Fix incorrect arguments being passed into vis.js

- R/transform_to_subgraph_ws.R
Been using the DiagrammeR package for some time. So great! 
I've run into what I think is a bug when `select_edges(edges = ...)` is used to select edges in a graph.
If there are multiple edges with the same from and to nodes specified yet they are not included in the `edges` vector they are still included in the subgraph.
This is my first git pull request *ever*. Way overdue. I'm open to suggestions in how to better suggest changes in these.
Thanks !!
Andrew Maffei
```
#
ndf <-
create_node_df(
n = 3,
value =
c(3.5, 2.6, 9.4))
edf <-
create_edge_df(
from = c(1, 2, 2),
to = c(2, 3, 3))
graph <-
create_graph(
nodes_df = ndf,
edges_df = edf)
graph <- graph %>%
clear_selection() %>%
select_edges(
edges = c(1,2))
subgraph <-
graph %>%
transform_to_subgraph_ws()
subgraph %>% get_node_df() …
```
> fix for transform_to_subgraph_ws for problem when selecting by edge id

- inst/htmlwidgets/DiagrammeR.js
- inst/htmlwidgets/grViz.js
This addresses #290 
For now a click on a node, creates a Shiny input object with node id and the text content. It would be nice to have some highlighting options too. But I hope this will do as a start.
Here's a test shiny-app:
```
library(DiagrammeR)
library(shiny)
graph <-
open_graph(
system.file(
"extdata/example_graphs_dgr/repository.dgr",
package = "DiagrammeR"))
ui <- fluidPage(
grVizOutput("dg")
, verbatimTextOutput("print")
, DiagrammeROutput("dg1")
, verbatimTextOutput("print1")
)
server <- function(input, output, session) {
output$dg <- renderGrViz({
render_graph(graph, layout = "kk")
})
output$print <- renderPrint({
req(input$dg_click)
print(unlist(input$dg_click))
})
output$dg1 <- renderDiagrammeR({
DiagrammeR("graph LR;A(Rounded)-->B[Squared];B-->C{A Decision};
C-->D[Square …
```
> add Shiny click events

- R/spectools.R
- tests/testthat/test-spectools.R
This simple fix to rich-iannone/DiagrammeR#357 removes the single quotes when doing @@1 style substitution. It also adds a test for the behaviour.
> fixes rich-iannone/DiagrammeR#357

- R/add_nodes_from_df_cols.R
- R/get_agg_degree_in.R
- R/get_agg_degree_out.R
- R/get_agg_degree_total.R
- R/get_edges.R
- R/layout_nodes_w_string.R
- R/mutate_edge_attrs.R
- R/mutate_edge_attrs_ws.R
- R/mutate_node_attrs.R
- R/mutate_node_attrs_ws.R
- R/select_nodes_by_degree.R
- R/to_igraph.R
- R/trav_both.R
- R/trav_both_edge.R
- R/trav_in.R
- R/trav_in_edge.R
- R/trav_in_node.R
- R/trav_out.R
- R/trav_out_edge.R
- R/trav_out_node.R
- R/trav_reverse_edge.R
- R/utils.R
I had saw that there were many warnings generated on tests, mostly because the deprecated dplyr underscore functions (like "select_") were being used. This removes those warnings and moves to the new dplyr style of using !! and quosures.
I did my best to make the minimal changes to move to the new functions, but in some cases I simplified the code because it was easier.
> Remove references to deprecated dplyr functions

- R/generate_dot.R
Fixes rich-iannone/DiagrammeR#403
Fix bug where unclustered nodes were being deleted if other nodes that are in clusters were present.  Problem was this line which has been deleted:
cluster_vals[cluster_vals == ""] <- NA_character_
made the non-clustered nodes get dropped when this line got run:
clusters <- split(node_block, cluster_vals)
Since elsewhere in the code, all NA values are converted to "", keeping non-clustered nodes with the "" value avoids them being dropped by split().
> Fix bug "clusters from data.frames broken? #403"

- NEWS.md
- R/grViz.R
- R/spectools.R
- man/grViz.Rd
- man/replace_in_spec.Rd
Currently, `replace_in_spec` calls `eval` with its default `envir` argument (i.e, `parent.frame()`).
This may cause object not found error in some cases.
Below is an reproducible example, which results error due to the `knit` parameter on YAML front matter.
Here, `rmarkdown::render` has `envir` argument (default: `parent.frame()`), and is causing `grViz` to find the object `foo`.
This PR fixes this problem.
````
---
title: "untitled"
output: html_vignette
knit: (function(...) rmarkdown::render(...))
---
```{r}
foo <- 'a'
DiagrammeR::grViz("digraph flowchart {
tab1 [label = '@@1']
tab1
}
[1]: foo
")
```
````
> add envir arguments to grViz and replace_in_spec

- R/colorize_edge_attrs.R
- R/colorize_node_attrs.R
- tests/testthat/test-colorize_nodes_edges.R
This is a fix for #289 and an analogous problem with `colorize_edge_attrs`.
For both edge (`colorize_edge_attrs`) and node (`colorize_node_attrs`) coloring, this verifies that any `palette` argument with length greater than 1 consists of valid hexadecimal colors. If it does and the number of elements is sufficient for the number of information levels to be encoded, the provided colors are used. When the number of provided colors is insufficient, the default palette of `viridis` is used.
There are also new tests to ensure the resulting colors are valid hexadecimal values and to check that invalid color inputs generate an error message.
> Fix user-provided hexadecimal node and edge coloring from issue 289

- R/colorize_edge_attrs.R
- R/colorize_node_attrs.R
- tests/testthat/test-colorize_nodes_edges.R
This fixes #436. 
The previous `colorize_node_attrs` and `colorize_edge_attrs` functions incorrectly assumed any valid hexadecimal color string would be contained in `x11_hex()$hex` but this excludes many valid colors. The new parameter check is less stringent and allows any case-insensitive match to the regular expression `"#[0-9A-F]{6}"`.
The testing code has been updated to include a hex color that is not in `x11_hex()`.
> Allow for hexadecimal colors not in named X11 colors

- R/generate_dot.R
We are updating `tidyr::replace_na()` to utilize vctrs, and that results in slightly stricter / more correct type conversions. See https://github.com/tidyverse/tidyr/pull/1219
We noticed in revdeps that this package indirectly broke 4 of our revdeps. An easy way to reproduce is to install that PR and run:
``` r
library(heuristicsmineR)
x <- causal_net(
L_heur_1,
type_nodes = causal_custom(attribute = "timestamp"),
type_edges = causal_custom(attribute = "timestamp")
)
rendered <- render_causal_net(x)
#> Error: Problem with `mutate()` column `color_level`.
#> ℹ `color_level = (structure(function (..., .x = ..1, .y = ..2, . = ..1) ...`.
#> x Can't convert `replace` <character> to match type of `data` <double>.
```
The problem boils down to the fact that, with the current …
> Only call `replace_na(replace = "")` on character columns

- R/render_graph.R
- man/DiagrammeR-package.Rd
Fix #492 
Naive fix, (harmless) doesn't change anything ) working on refactoring the `render_graph()` code to silence some tibble related warnings, but thought I'd send this as a separate PR.
I ran into an error that only shows up when dev (with load_all() when testing this. (that I do not understand)
```r
<std::runtime_error> with text:
ReferenceError: Viz is not defined
Warnings
In file(con, "r") :
file("") accepts only open = "w+" and open = "w+b" : using the first one
```
If you have an idea what it means, please let me know.
But I was able to test it successfully by installing the dev version of DIagrammeR locally.
> Add display to code when saving `as_svg = TRUE`

- DESCRIPTION
- R/DiagrammeR.R
- R/import_graph.R
- _pkgdown.yml
- man/DiagrammeR.Rd
The search function doesn't work as intended currently on the website.
Search for mermaid to see. If this PR doesn't fix the issue, I will change clean from true to false temporarily on the pkgdown gh action.
https://rich-iannone.github.io/DiagrammeR/ and type "mermaid" in the search bar.
I added some trivial changes as well.
> Fix pkgdown config and move curl to Suggests

- NEWS.md
- R/render_graph.R
- man/render_graph.Rd
- tests/testthat/test-render_graph.R
Basically, I refactored the code by:
1. return early if output is vistnetwork. (hence the large diff, no longer to nest the code in a if condition)
2. Use vectors to access the matrix columns instead of using `as_tibble()`
3. We error earlier if the layout is not in one of the allowed values
4. I take some of the common code for each layout and avoid code duplication, only applying correction for the `"circle"` layout.
5. Added tests to verify no warning were produced.
I was also able to simplify a condition
```r
y * (((count_nodes(graph) + (0.25 * count_nodes(graph)))) / count_nodes(graph)))
y * 1.25
```
I suggest looking at the diff side by side since it doesn't look too good inline.
The example in README
```r
library(DiagrammeR)
example_graph <-
create_graph() %>%
add_pa_graph(
n = 50, …
```
> Remove tibble warnings in `render_graph()`

- DESCRIPTION
- NEWS.md
- R/DiagrammeR-package.R
- R/colorize_edge_attrs.R
- R/colorize_node_attrs.R
- man/DiagrammeR-package.Rd
Makes the package a bit lighter as we only use `viridis::virdis()` which is re-exported from viridisLite anyway. This removes 9 dependencies overall.
> Use viridisLite instead of viridis + redocument

- R/generate_dot.R
Previously, edge attribute is generated based on whether `colnames(edges_df)[j]` is in selected attributes and the content for current edge `edges_df[i, j]` is valid.
The checks on `edges_df[i, j]` is whether it is `NA` or not empty string. But this logic is not closed since `edges_df[i, j]` can be empty string (''). This is possible since in previous code in `generate_dot()`, empty attributes have been set to empty string, not NA. This will lead to some bad behavior:
1. If the 1st edge does not have attributes set, this function will throw a "object 'attribute' not found" error. #440 
2. If the previous edge has some attributes set while latters don't, then the previous attributes will be carried over to latter edges since `attribute` is not properly set to `NULL` at the beginning for …
> Update the logic of edge attribute generation
